keymap = [
    # Motion
    { key = "u", run = "move up"          },
    { key = "e", run = "move down"        },
    { key = "n", run = "move left"        },
    { key = "i", run = "move right"       },
    { key = "G", run = "goto_bottom"      },
    { key = "v", run = "list_scroll next" },
    { key = "V", run = "list_scroll prev" },

    # Operations with menu
    { key = "t", run = "tab_operation"    },
    { key = "g", run = "goto_operation"   },
    { key = "p", run = "paste_operation"  },
    { key = "d", run = "delete_operation" },

    # Search
    { key = "/", run = "search"              },
    { key = "k", run = "move_candidate next" },
    { key = "K", run = "move_candidate prev" },

    # Mark
    { key = "m", run = "mark all"    },
    { key = " ", run = "mark single" },
    { key = "M", run = "mark_expand" },

    # File Create
    { key = "+", run = "create_dir"  },
    { key = "=", run = "create_file" },

    # Shell
    { key = "S", run = "spawn_shell"                },
    { key = "!", run = "cmdline_shell"              },
    { key = "l", run = "shell_command true lazygit" },

    # File name modify
    { key = "a", run = "append_filename name"      },
    { key = "A", run = "append_filename extension" },

    # Working directory
    { key = "W", run = "work_directory set"  },
    { key = "w", run = "work_directory goto" },

    # Others
    { key = "R", run = "refresh"               },
    { key = "f", run = "fzf_jump"              },
    { key = "P", run = "full_path"             },
    { key = "i", run = "edit_mode"             },
    { key = "-", run = "hide_or_show"          },
    { key = "s", run = "single_symlink"        },
    { key = "\\", run = "change_output_status" },

    # Navigation Index
    { key = "1", run = "navi_input 1"    },
    { key = "2", run = "navi_input 2"    },
    { key = "3", run = "navi_input 3"    },
    { key = "4", run = "navi_input 4"    },
    { key = "5", run = "navi_input 5"    },
    { key = "6", run = "navi_input 6"    },
    { key = "7", run = "navi_input 7"    },
    { key = "8", run = "navi_input 8"    },
    { key = "9", run = "navi_input 9"    },
    { key = "0", run = "navi_input 0"    },
    { key = ".", run = "show_navi_index" },

    # Edit Mode
    { key = "Q", run = "quit_edit"             },
    { key = "g", run = "edit_top"              },
    { key = "G", run = "edit_bottom"           },
    { key = "d", run = "edit_delete"           },
    { key = "K", run = "edit_new dir"          },
    { key = "k", run = "edit_new file"         },
    { key = "u", run = "edit_move prev"        },
    { key = "e", run = "edit_move next"        },
    { key = "m", run = "edit_mark all"         },
    { key = " ", run = "edit_mark single"      },
    { key = "h", run = "edit_insert end"       },
    { key = "H", run = "edit_insert beg"       },
    { key = "v", run = "edit_list_scroll next" },
    { key = "V", run = "edit_list_scroll prev" },
]